FROM node:20-alpine AS build

WORKDIR /app

COPY app/package.json app/package-lock.json ./

ARG VITE_DEFAULT_API_MODE=live
ARG VITE_LIVE_API_BASE_URL=https://patrabackend.pods.icicleai.tapis.io
ARG VITE_MOCK_API_BASE_URL=http://localhost:5003
ARG VITE_SUPPORTS_AGENT_TOOLS=false
ARG VITE_SUPPORTS_EDIT_RECORDS=true
ARG VITE_SUPPORTS_TICKETS=false
ARG VITE_USE_V1_ASSET_CREATE=true
ARG VITE_ASSET_ORG=
ARG VITE_ASSET_API_KEY=
ARG VITE_SUPPORTS_EDIT_EXISTING_RESOURCES=false
ARG VITE_SUPPORTS_AUTOMATED_INGESTION=false
ARG VITE_SUPPORTS_ASK_PATRA=false
ARG VITE_SUPPORTS_MCP_EXPLORER=true
ARG VITE_SUPPORTS_DOMAIN_EXPERIMENTS=true
ARG VITE_MCP_BASE_URL=http://localhost:8050

ENV VITE_DEFAULT_API_MODE=${VITE_DEFAULT_API_MODE}
ENV VITE_LIVE_API_BASE_URL=${VITE_LIVE_API_BASE_URL}
ENV VITE_MOCK_API_BASE_URL=${VITE_MOCK_API_BASE_URL}
ENV VITE_SUPPORTS_AGENT_TOOLS=${VITE_SUPPORTS_AGENT_TOOLS}
ENV VITE_SUPPORTS_EDIT_RECORDS=${VITE_SUPPORTS_EDIT_RECORDS}
ENV VITE_SUPPORTS_TICKETS=${VITE_SUPPORTS_TICKETS}
ENV VITE_USE_V1_ASSET_CREATE=${VITE_USE_V1_ASSET_CREATE}
ENV VITE_ASSET_ORG=${VITE_ASSET_ORG}
ENV VITE_ASSET_API_KEY=${VITE_ASSET_API_KEY}
ENV VITE_SUPPORTS_EDIT_EXISTING_RESOURCES=${VITE_SUPPORTS_EDIT_EXISTING_RESOURCES}
ENV VITE_SUPPORTS_AUTOMATED_INGESTION=${VITE_SUPPORTS_AUTOMATED_INGESTION}
ENV VITE_SUPPORTS_ASK_PATRA=${VITE_SUPPORTS_ASK_PATRA}
ENV VITE_SUPPORTS_MCP_EXPLORER=${VITE_SUPPORTS_MCP_EXPLORER}
ENV VITE_SUPPORTS_DOMAIN_EXPERIMENTS=${VITE_SUPPORTS_DOMAIN_EXPERIMENTS}
ENV VITE_MCP_BASE_URL=${VITE_MCP_BASE_URL}

RUN npm ci

COPY app/ ./

RUN npm run build

FROM nginx:1.27-alpine

ARG VITE_LIVE_API_BASE_URL=https://patrabackend.pods.icicleai.tapis.io
ENV API_BASE_URL=${VITE_LIVE_API_BASE_URL}

ARG VITE_SUPPORTS_AGENT_TOOLS=false
ARG VITE_SUPPORTS_EDIT_RECORDS=true
ARG VITE_SUPPORTS_TICKETS=false
ARG VITE_USE_V1_ASSET_CREATE=true
ARG VITE_ASSET_ORG=
ARG VITE_ASSET_API_KEY=
ARG VITE_SUPPORTS_EDIT_EXISTING_RESOURCES=false
ARG VITE_SUPPORTS_AUTOMATED_INGESTION=false
ARG VITE_SUPPORTS_ASK_PATRA=false
ARG VITE_SUPPORTS_MCP_EXPLORER=true
ARG VITE_SUPPORTS_DOMAIN_EXPERIMENTS=true
ARG VITE_MCP_BASE_URL=http://localhost:8050
ENV SUPPORTS_AGENT_TOOLS=${VITE_SUPPORTS_AGENT_TOOLS}
ENV SUPPORTS_EDIT_RECORDS=${VITE_SUPPORTS_EDIT_RECORDS}
ENV SUPPORTS_TICKETS=${VITE_SUPPORTS_TICKETS}
ENV USE_V1_ASSET_CREATE=${VITE_USE_V1_ASSET_CREATE}
ENV ASSET_ORG=${VITE_ASSET_ORG}
ENV ASSET_API_KEY=${VITE_ASSET_API_KEY}
ENV SUPPORTS_EDIT_EXISTING_RESOURCES=${VITE_SUPPORTS_EDIT_EXISTING_RESOURCES}
ENV SUPPORTS_AUTOMATED_INGESTION=${VITE_SUPPORTS_AUTOMATED_INGESTION}
ENV SUPPORTS_ASK_PATRA=${VITE_SUPPORTS_ASK_PATRA}
ENV SUPPORTS_MCP_EXPLORER=${VITE_SUPPORTS_MCP_EXPLORER}
ENV SUPPORTS_DOMAIN_EXPERIMENTS=${VITE_SUPPORTS_DOMAIN_EXPERIMENTS}
ENV MCP_BASE_URL=${VITE_MCP_BASE_URL}

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY deploy/frontend-env.sh /docker-entrypoint.d/40-patra-env.sh
COPY --from=build /app/dist /usr/share/nginx/html
RUN sed -i 's/\r$//' /docker-entrypoint.d/40-patra-env.sh \
  && chmod +x /docker-entrypoint.d/40-patra-env.sh

EXPOSE 80
