#!/bin/sh
set -eu

LIVE_API_BASE_URL="${API_BASE_URL:-${VITE_LIVE_API_BASE_URL:-http://localhost:8000}}"
MOCK_API_BASE_URL="${MOCK_API_BASE_URL:-${VITE_MOCK_API_BASE_URL:-http://localhost:5003}}"
DEFAULT_API_MODE="${DEFAULT_API_MODE:-${VITE_DEFAULT_API_MODE:-live}}"
SHOW_API_MODE="${SHOW_API_MODE:-${VITE_SHOW_API_MODE:-false}}"
SUPPORTS_TICKETS="${SUPPORTS_TICKETS:-${VITE_SUPPORTS_TICKETS:-true}}"
SUPPORTS_SUBMISSIONS_API="${SUPPORTS_SUBMISSIONS_API:-${VITE_SUPPORTS_SUBMISSIONS_API:-true}}"
ADMIN_USERNAMES="${ADMIN_USERNAMES:-${VITE_ADMIN_USERNAMES:-williamq96}}"

cat > /usr/share/nginx/html/env.js <<EOF
window.__PATRA_CONFIG__ = {
  API_BASE_URL: "${LIVE_API_BASE_URL}",
  MOCK_API_BASE_URL: "${MOCK_API_BASE_URL}",
  DEFAULT_API_MODE: "${DEFAULT_API_MODE}",
  SHOW_API_MODE: "${SHOW_API_MODE}",
  SUPPORTS_TICKETS: "${SUPPORTS_TICKETS}",
  SUPPORTS_SUBMISSIONS_API: "${SUPPORTS_SUBMISSIONS_API}",
  ADMIN_USERNAMES: "${ADMIN_USERNAMES}"
};
EOF
