#!/bin/sh
set -eu

LIVE_API_BASE_URL="${API_BASE_URL:-${VITE_LIVE_API_BASE_URL:-http://localhost:8000}}"
MOCK_API_BASE_URL="${MOCK_API_BASE_URL:-${VITE_MOCK_API_BASE_URL:-http://localhost:5003}}"
DEFAULT_API_MODE="${DEFAULT_API_MODE:-${VITE_DEFAULT_API_MODE:-live}}"
SHOW_API_MODE="${SHOW_API_MODE:-${VITE_SHOW_API_MODE:-false}}"
SUPPORTS_TICKETS="${SUPPORTS_TICKETS:-${VITE_SUPPORTS_TICKETS:-false}}"
SUPPORTS_SUBMISSIONS_API="${SUPPORTS_SUBMISSIONS_API:-${VITE_SUPPORTS_SUBMISSIONS_API:-true}}"
SUPPORTS_AGENT_TOOLS="${SUPPORTS_AGENT_TOOLS:-${VITE_SUPPORTS_AGENT_TOOLS:-false}}"
SUPPORTS_EDIT_RECORDS="${SUPPORTS_EDIT_RECORDS:-${VITE_SUPPORTS_EDIT_RECORDS:-true}}"
SUPPORTS_EDIT_EXISTING_RESOURCES="${SUPPORTS_EDIT_EXISTING_RESOURCES:-${VITE_SUPPORTS_EDIT_EXISTING_RESOURCES:-${SUPPORTS_EDIT_RECORDS}}}"
SUPPORTS_AUTOMATED_INGESTION="${SUPPORTS_AUTOMATED_INGESTION:-${VITE_SUPPORTS_AUTOMATED_INGESTION:-false}}"
SUPPORTS_ASK_PATRA="${SUPPORTS_ASK_PATRA:-${VITE_SUPPORTS_ASK_PATRA:-false}}"
SUPPORTS_INTENT_SCHEMA="${SUPPORTS_INTENT_SCHEMA:-${VITE_SUPPORTS_INTENT_SCHEMA:-false}}"
SUPPORTS_MCP_EXPLORER="${SUPPORTS_MCP_EXPLORER:-${VITE_SUPPORTS_MCP_EXPLORER:-false}}"
SUPPORTS_DOMAIN_EXPERIMENTS="${SUPPORTS_DOMAIN_EXPERIMENTS:-${VITE_SUPPORTS_DOMAIN_EXPERIMENTS:-false}}"
SUPPORTS_DEV_OPEN_ACCESS="${SUPPORTS_DEV_OPEN_ACCESS:-${VITE_SUPPORTS_DEV_OPEN_ACCESS:-false}}"
ADMIN_USERNAMES="${ADMIN_USERNAMES:-${VITE_ADMIN_USERNAMES:-williamq96,neelk}}"
USE_V1_ASSET_CREATE="${USE_V1_ASSET_CREATE:-${VITE_USE_V1_ASSET_CREATE:-true}}"
ASSET_ORG="${ASSET_ORG:-${VITE_ASSET_ORG:-}}"
ASSET_API_KEY="${ASSET_API_KEY:-${VITE_ASSET_API_KEY:-}}"
MCP_BASE_URL="${MCP_BASE_URL:-${VITE_MCP_BASE_URL:-http://localhost:8050}}"

cat > /usr/share/nginx/html/env.js <<EOF
window.__PATRA_CONFIG__ = {
  API_BASE_URL: "${LIVE_API_BASE_URL}",
  MOCK_API_BASE_URL: "${MOCK_API_BASE_URL}",
  DEFAULT_API_MODE: "${DEFAULT_API_MODE}",
  SHOW_API_MODE: "${SHOW_API_MODE}",
  SUPPORTS_TICKETS: "${SUPPORTS_TICKETS}",
  SUPPORTS_SUBMISSIONS_API: "${SUPPORTS_SUBMISSIONS_API}",
  SUPPORTS_AGENT_TOOLS: "${SUPPORTS_AGENT_TOOLS}",
  SUPPORTS_EDIT_EXISTING_RESOURCES: "${SUPPORTS_EDIT_EXISTING_RESOURCES}",
  SUPPORTS_EDIT_RECORDS: "${SUPPORTS_EDIT_EXISTING_RESOURCES}",
  SUPPORTS_AUTOMATED_INGESTION: "${SUPPORTS_AUTOMATED_INGESTION}",
  SUPPORTS_ASK_PATRA: "${SUPPORTS_ASK_PATRA}",
  SUPPORTS_INTENT_SCHEMA: "${SUPPORTS_INTENT_SCHEMA}",
  SUPPORTS_MCP_EXPLORER: "${SUPPORTS_MCP_EXPLORER}",
  SUPPORTS_DOMAIN_EXPERIMENTS: "${SUPPORTS_DOMAIN_EXPERIMENTS}",
  SUPPORTS_DEV_OPEN_ACCESS: "${SUPPORTS_DEV_OPEN_ACCESS}",
  ADMIN_USERNAMES: "${ADMIN_USERNAMES}",
  USE_V1_ASSET_CREATE: "${USE_V1_ASSET_CREATE}",
  ASSET_ORG: "${ASSET_ORG}",
  ASSET_API_KEY: "${ASSET_API_KEY}",
  MCP_BASE_URL: "${MCP_BASE_URL}"
};
EOF
